# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1efgBbRhLvjJOsWCHy07bb53yhEw3FxXX

#Start -- downloads and installations

Install the [MiDiTok](https://github.com/Natooz/MidiTok) package, which simplifies MIDI file processing by making note and beat extraction more straightforward.
"""

!pip install nbconvert

!jupyter nbconvert --to html /content/drive/MyDrive/Colab_Notebooks/assignment2.ipynb

! pip install miditok
! pip install midiutil
! pip install midi2audio
! pip install miditoolkit

!apt-get install -y fluidsynth
!pip install midi2audio
!wget https://raw.githubusercontent.com/musescore/MuseScore/master/share/sound/FluidR3Mono_GM.sf3

# import required packages
import random
from glob import glob
from collections import defaultdict

import numpy as np
from numpy.random import choice
import math

from symusic import Score
from miditok import REMI, TokenizerConfig
from midiutil import MIDIFile

from miditok.pytorch_data import DatasetMIDI, DataCollator
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from midi2audio import FluidSynth
from IPython.display import Audio, display

import miditoolkit
import pickle
import os

# keep results deterministic
random.seed(42)

"""### Load music dataset
Using [GiantMIDI-Piano](https://github.com/bytedance/GiantMIDI-Piano?tab=readme-ov-file) dataset
"""

from google.colab import drive
drive.mount('/content/drive')

# import zipfile

# zip_path = "/content/drive/MyDrive/CSE253/assignment2/GiantMIDI-PIano/midis_v1.2.zip"
# extract_to = "/content/drive/MyDrive/CSE253/assignment2/unzipped/"

# with zipfile.ZipFile(zip_path, 'r') as zip_ref:
#     zip_ref.extractall(extract_to)

midi_files = glob('/content/drive/MyDrive/CSE253/assignment2/unzipped/midis/*.mid')

len(midi_files)

"""# Part 1: Symbolic, unconditioned generation:

###Split into train/test data
"""

train_data = midi_files[:len(midi_files) // 2]
test_data  = midi_files[len(midi_files) // 2:]

len(train_data), len(test_data)

"""###Train tokenizer"""

tokenizer = REMI()  # using defaults parameters (constants.py)
train_dataset = DatasetMIDI(
    files_paths=train_data,
    tokenizer=tokenizer,
    max_seq_len=1024,
    bos_token_id=tokenizer["BOS_None"],
    eos_token_id=tokenizer["EOS_None"],
)
test_dataset = DatasetMIDI(
    files_paths=test_data,
    tokenizer=tokenizer,
    max_seq_len=1024,
    bos_token_id=tokenizer["BOS_None"],
    eos_token_id=tokenizer["EOS_None"],
)
collator = DataCollator(tokenizer.pad_token_id)
train_loader1 = DataLoader(train_dataset, batch_size=4, shuffle=True, collate_fn=collator)
test_loader1 = DataLoader(test_dataset, batch_size=4, shuffle=False, collate_fn=collator)

len(train_loader1), len(test_loader1)

"""###Define RNN model"""

class MusicRNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, num_layers):
        super(MusicRNN, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.rnn = nn.LSTM(
            input_size=embedding_dim,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True
        )
        self.fc = nn.Linear(hidden_dim, vocab_size)

    def forward(self, x, hidden=None):
        # x: (batch_size, seq_length)
        x = self.embedding(x)  # (batch_size, seq_length, embedding_dim)
        out, hidden = self.rnn(x, hidden)  # out: (batch_size, seq_length, hidden_dim)
        out = self.fc(out)  # (batch_size, seq_length, vocab_size)
        return out, hidden

"""### Training"""

def train(model, train_loader, val_loader, vocab_size, num_epochs=10, lr=0.001, device='cuda'):
    model = model.to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    for epoch in range(num_epochs):
        # --------- Training ---------
        model.train()
        total_train_loss = 0

        batch_num = 0
        for batch in train_loader:
            batch_num += 1
            if batch_num % 100 == 0:
              print(f"Training Batch {batch_num}/{len(train_loader)}")
            batch = batch['input_ids'].to(device)  # (batch_size, seq_length)

            inputs = batch[:, :-1]
            targets = batch[:, 1:]

            optimizer.zero_grad()
            outputs, _ = model(inputs)
            outputs = outputs.reshape(-1, vocab_size)
            targets = targets.reshape(-1)

            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()

            total_train_loss += loss.item()

        avg_train_loss = total_train_loss / len(train_loader)

        # --------- Validation ---------
        model.eval()
        total_val_loss = 0
        with torch.no_grad():
            batch_num = 0
            for batch in val_loader:
                batch_num += 1
                if batch_num % 100 == 0:
                  print(f"Testing Batch {batch_num}/{len(val_loader)}")
                batch = batch['input_ids'].to(device)

                inputs = batch[:, :-1]
                targets = batch[:, 1:]

                outputs, _ = model(inputs)
                outputs = outputs.reshape(-1, vocab_size)
                targets = targets.reshape(-1)

                loss = criterion(outputs, targets)
                total_val_loss += loss.item()

        avg_val_loss = total_val_loss / len(val_loader)

        print(f"Epoch {epoch+1}/{num_epochs} | Train Loss: {avg_train_loss:.4f} | Val Loss: {avg_val_loss:.4f}")

    torch.save(model.state_dict(), "symbolicUncond_model.pth")


if __name__ == "__main__":
    vocab_size = tokenizer.vocab_size
    embedding_dim = 256
    hidden_dim = 512
    num_layers = 2

    model1 = MusicRNN(vocab_size, embedding_dim, hidden_dim, num_layers)
    # train(model, train_loader, test_loader, vocab_size)

model1.load_state_dict(torch.load("/content/drive/MyDrive/CSE253/assignment2/symbolicUncond_model.pth"))

"""### Sampling"""

def sample(model, start_token, max_length=100, temperature=1.0, device='cuda'):
    model = model.to(device)
    model.eval()

    generated = [start_token]
    input_token = torch.tensor([[start_token]], device=device)  # (1, 1)

    hidden = None

    for _ in range(max_length):
        output, hidden = model(input_token, hidden)  # output: (1, 1, vocab_size)
        output = output[:, -1, :]  # take the last output
        output = output / temperature  # adjust randomness

        probs = F.softmax(output, dim=-1)  # (1, vocab_size)
        next_token = torch.multinomial(probs, num_samples=1).item()
        generated.append(next_token)
        if next_token == 2 or next_token == 0: # reach end of sequence
          break

        input_token = torch.tensor([[next_token]], device=device)

    return generated

start_token = tokenizer.special_tokens_ids[1]
generated_sequence = sample(model1, start_token, max_length=2024)

print("Generated token sequence:")
print(generated_sequence)

"""### Generate audio"""

fs = FluidSynth("FluidR3Mono_GM.sf3") # Initialize FluidSynth

output_score = tokenizer.tokens_to_midi([generated_sequence])
output_score.dump_midi(f"symbolic_unconditioned2.mid")
fs.midi_to_audio("symbolic_unconditioned2.mid", "symbolic_unconditioned.wav")
display(Audio("symbolic_unconditioned.wav"))

torch.save(model.state_dict(), "/content/drive/MyDrive/CSE253/assignment2/symbolicUncond_model.pth")

"""###Evaluate Model 1


"""

def evaluate_perplexity1(model, test_loader, vocab_size, device='cuda'):
    model = model.to(device)
    model.eval()
    criterion = torch.nn.CrossEntropyLoss()
    total_val_loss = 0

    with torch.no_grad():
        for batch in test_loader:
            batch = batch['input_ids'].to(device)
            inputs = batch[:, :-1]
            targets = batch[:, 1:]

            outputs, _ = model(inputs)
            outputs = outputs.reshape(-1, vocab_size)
            targets = targets.reshape(-1)

            loss = criterion(outputs, targets)
            total_val_loss += loss.item()

    avg_val_loss = total_val_loss / len(test_loader)
    perplexity = math.exp(avg_val_loss)
    return perplexity

ppl1 = evaluate_perplexity1(model1, test_loader1, tokenizer.vocab_size, device='cuda')
print(f"Test Perplexity: {ppl1:.2f}")

"""##Bigram model"""

config = TokenizerConfig(num_velocities=1, use_chords=False, use_programs=False)
bigram_tokenizer = REMI(config)
bigram_tokenizer.train(vocab_size=1000, files_paths=train_data)

def note_extraction(midi_file):
    midi = Score(midi_file)
    tokens = bigram_tokenizer(midi)[0].tokens
    pitch_list = []

    for event in tokens:
      if "Pitch" in event:
         num = "".join([c for c in event if c.isdigit()]) #extract digit
         pitch_list.append(int(num))
    return pitch_list

def note_frequency(midi_files):
    freqCount = {}
    for mFile in midi_files:
      pitch_list = note_extraction(mFile)
      for note in pitch_list:
        if note in freqCount:
          freqCount[note] += 1
        else:
          freqCount[note] = 1

    return freqCount

def note_unigram_probability(midi_files):
    note_counts = note_frequency(midi_files)
    unigramProbabilities = {}

    total = sum(note_counts.values())
    for key, value in note_counts.items():
      unigramProbabilities[key] = value/total

    return unigramProbabilities

def note_bigram_probability(midi_files):
    bigramTransitions = defaultdict(list)
    bigramTransitionProbabilities = defaultdict(list)

    #collect the bigrams
    bigrams = defaultdict(int)
    for mFile in midi_files:
      pitch_list = note_extraction(mFile)
      for (chord1,chord2) in zip(pitch_list[:-1],pitch_list[1:]):
        bigrams[(chord1,chord2)] += 1

    #use the bigrams (already unique and counted)
    transitionCounts = defaultdict(list)
    for key, value in bigrams.items():
      bigramTransitions[key[0]].append(key[1])
      transitionCounts[key[0]].append(value)

    #normalize counts into probabilities
    for key, value in transitionCounts.items():
      total = sum(value)
      for count in value:
        bigramTransitionProbabilities[key].append(count/total)

    return bigramTransitions, bigramTransitionProbabilities

def note_bigram_perplexity(midi_file):
    unigramProbabilities = note_unigram_probability(train_data)
    bigramTransitions, bigramTransitionProbabilities = note_bigram_probability(train_data)

    #sequence in midi file
    actual = note_extraction(midi_file)

    #prob get that sequence
    total = 0
    N = len(actual)
    for i in range(N):
      curr = actual[i]
      if i == 0:
        total += np.log(unigramProbabilities[curr]) #p(w1)
      else:
        prev = actual[i-1]
        for j in range(len(bigramTransitions[prev])):
          if bigramTransitions[prev][j] == curr: #aligning with probs list
            index = j
        total += np.log(bigramTransitionProbabilities[prev][index])

    #equation
    return (np.exp((-1/N)*total))

bigram_perplexity = 0
valid_files = 0

for file in test_data:
    try:
        bigram_perplexity += note_bigram_perplexity(file)
        valid_files += 1
    except Exception as e:
        print(f"Error processing {file}: {e}")
        print("processed valid files:", valid_files)

if valid_files > 0:
    avg_bigram = bigram_perplexity / valid_files
    print(f"Average Bigram Perplexity: {avg_bigram:.4f}")
else:
    print("No valid files for bigram perplexity.")

"""#Part 2: Symbolic, conditioned generation:

###Preprocessing: filter parts want to use as condition
- Predictor = chord

- Target = note harmony
"""

# Map melody to chords

#chords = start and end together
#harmony = notes that play in between that time

def extract_map(midi_file):
  midi_obj = miditoolkit.midi.parser.MidiFile(midi_file)
  ticks_per_beat = midi_obj.ticks_per_beat
  notes = midi_obj.instruments[0].notes
  max_time = max(n.end for n in notes)

  examples = []
  for t in range(0, max_time, ticks_per_beat):
      chord_notes = [n.pitch for n in notes if n.start <= t < n.end]
      # Get chord
      if len(chord_notes) < 3:
          continue

      # Get melody (highest pitch in this window)
      window_notes = [n for n in notes if t <= n.start < t + ticks_per_beat]
      if not window_notes:
          continue
      melody_note = max(window_notes, key=lambda n: n.pitch).pitch

      examples.append((chord_notes, melody_note))
  return examples

all_examples = []
save_path = "/content/drive/MyDrive/CSE253/assignment2/all_examples.pkl"
checkpoint_interval = 50

for i, midi_file in enumerate(midi_files):
    try:
        examples = extract_map(midi_file)
        all_examples.extend(examples)

        if i % checkpoint_interval == 0:
            print(f"Processed {i} files")
            with open(save_path, "wb") as f:
                pickle.dump(all_examples, f)

    except Exception as e:
        print(f"Error processing on: {i}, {e}")

# Final save
with open(save_path, "wb") as f:
    pickle.dump(all_examples, f)

# Load
with open("/content/drive/MyDrive/CSE253/assignment2/all_examples.pkl", "rb") as f:
    all_examples = pickle.load(f)

"""###Split into train/test data"""

def normalize_chord(chord_notes):
    # [60, 64, 67] → (0, 4, 7)
    pcs = sorted(set(p % 12 for p in chord_notes))
    return tuple(pcs)

chord_set = set(normalize_chord(chord) for chord, _ in all_examples)
chord_vocab = {chord: i for i, chord in enumerate(sorted(chord_set))}

class ChordMelodyDataset(Dataset):
    def __init__(self, midi_files, chord_vocab, save_path, checkpoint_interval=50):
        self.data = []
        self.chord_vocab = chord_vocab
        self.pitch_min = 21
        self.pitch_max = 108
        self.save_path = save_path
        self.checkpoint_interval = checkpoint_interval

        for i, file in enumerate(midi_files):
            try:
                examples = extract_map(file)  # returns [(chord_notes, melody_note)]
                for chord_notes, note in examples:
                    pcs = tuple(sorted(set(p % 12 for p in chord_notes)))
                    if pcs in chord_vocab and self.pitch_min <= note <= self.pitch_max:
                        self.data.append((chord_vocab[pcs], note - self.pitch_min))

                # Save every N files
                if i % checkpoint_interval == 0:
                    print(f"Processed {i} files")
                    with open(save_path, "wb") as f:
                        pickle.dump(self.data, f)

            except Exception as e:
                print(f"Error processing {file}: {e}")

        with open(save_path, "wb") as f:
            pickle.dump(self.data, f)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        chord_token, note_token = self.data[idx]
        return {"chord": chord_token, "melody": note_token}

# train_dataset = ChordMelodyDataset(train_data, chord_vocab, "/content/drive/MyDrive/CSE253/assignment2/train_data2.pkl")
# test_dataset = ChordMelodyDataset(test_data, chord_vocab, "/content/drive/MyDrive/CSE253/assignment2/test_data2.pkl")

with open("/content/drive/MyDrive/CSE253/assignment2/train_data2.pkl", "rb") as f:
    train_dataset = pickle.load(f)

from torch.utils.data import random_split

train_ratio = 0.8
train_size = int(train_ratio * len(train_dataset))
test_size = len(train_dataset) - train_size

train_dataset, test_dataset = random_split(train_dataset, [train_size, test_size])
print("train dataset length:", len(train_dataset), \
      "\ntest dataset length:", len(test_dataset), \
      "\ntotal:", len(train_dataset) + len(test_dataset))

def collator(batch):
    chords = [item[0] for item in batch]
    melody = [item[1] for item in batch]
    return {
        "chords": torch.tensor(chords, dtype=torch.long),
        "melodies": torch.tensor(melody, dtype=torch.long)
    }

train_loader2 = DataLoader(train_dataset, batch_size=4, shuffle=True, collate_fn=collator)
test_loader2 = DataLoader(test_dataset, batch_size=4, shuffle=False, collate_fn=collator)

print("train_loader length:", len(train_loader2), \
      "\ntest_loader length:", len(test_loader2))

"""###Define model"""

class HarmonyRNN(nn.Module):
    def __init__(self, chord_vocab_size, embedding_dim, hidden_dim, num_layers, melody_vocab_size):
        super(HarmonyRNN, self).__init__()
        self.embedding = nn.Embedding(chord_vocab_size, embedding_dim)
        self.rnn = nn.LSTM(
            input_size=embedding_dim,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True
        )
        self.fc1 = nn.Linear(hidden_dim, hidden_dim // 2)
        self.fc2 = nn.Linear(hidden_dim // 2, melody_vocab_size)

    def forward(self, x, hidden=None):
        x = self.embedding(x)
        out, hidden = self.rnn(x, hidden)
        out = F.relu(self.fc1(out))
        out = self.fc2(out)
        return out, hidden

model2 = HarmonyRNN(
    chord_vocab_size=len(chord_vocab),
    embedding_dim=256,
    hidden_dim=512,
    num_layers=2,
    melody_vocab_size=88
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model2.to(device)

"""###Train"""

def train(model, train_loader, val_loader, melody_vocab_size, num_epochs=10, lr=0.001, device='cuda'):
    model = model.to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    for epoch in range(num_epochs):
        model.train()
        total_train_loss = 0

        for batch_num, batch in enumerate(train_loader, 1):
            chords = batch['chords'].to(device)    # (batch_size, seq_len)
            melodies = batch['melodies'].to(device)  # (batch_size, seq_len)

            optimizer.zero_grad()
            outputs, _ = model(chords)  # (batch_size, seq_len, melody_vocab_size)
            outputs = outputs.reshape(-1, melody_vocab_size)  # flatten for loss
            targets = melodies.reshape(-1)

            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()

            total_train_loss += loss.item()

            if batch_num % 1000 == 0:
                print(f"Training Batch {batch_num}/{len(train_loader)}")

        avg_train_loss = total_train_loss / len(train_loader)

        # Validation
        model.eval()
        total_val_loss = 0
        with torch.no_grad():
            for batch_num, batch in enumerate(val_loader, 1):
                chords = batch['chords'].to(device)
                melodies = batch['melodies'].to(device)

                outputs, _ = model(chords)
                outputs = outputs.reshape(-1, melody_vocab_size)
                targets = melodies.reshape(-1)

                loss = criterion(outputs, targets)
                total_val_loss += loss.item()

                if batch_num % 100 == 0:
                    print(f"Validation Batch {batch_num}/{len(val_loader)}")

        avg_val_loss = total_val_loss / len(val_loader)
        print(f"Epoch {epoch+1}/{num_epochs} | Train Loss: {avg_train_loss:.4f} | Val Loss: {avg_val_loss:.4f}")

    # torch.save(model.state_dict(), "harmony_rnn.pth")

train(
    model=model2,
    train_loader=train_loader2,
    val_loader=test_loader2,
    melody_vocab_size=88,
    device='cuda' if torch.cuda.is_available() else 'cpu'
)

"""###Generate harmony"""

# torch.save(model2.state_dict(), "/content/drive/MyDrive/CSE253/assignment2/cond_model.pth")

model2.load_state_dict(torch.load("/content/drive/MyDrive/CSE253/assignment2/cond_model.pth"))

def generate_melody(model, chord_sequence, temperature=1.0, device='cuda'):
    model.eval()
    chord_sequence = torch.tensor(chord_sequence, device=device).unsqueeze(0)  # (1, seq_len)

    with torch.no_grad():
        outputs, _ = model(chord_sequence)  # (1, seq_len, melody_vocab_size)
        logits = outputs.squeeze(0)  # (seq_len, melody_vocab_size)
        logits = logits / temperature
        probs = torch.softmax(logits, dim=-1)
        melody_tokens = torch.multinomial(probs, num_samples=1).squeeze(-1)  # (seq_len)

    return melody_tokens.cpu().tolist()

"""###Transform to audio"""

def create_midi(chord_seq, melody_seq, output_path):
    midi_obj = miditoolkit.MidiFile()
    piano = miditoolkit.Instrument(program=0)  # Acoustic Grand Piano

    # Example: align chords and melody notes per timestep (assuming fixed duration)
    time_per_step = 480 * 3
    time = 0

    for chord_pcs, melody_pitches in zip(chord_seq, melody_seq):
        # Add chord notes
        for pc in chord_pcs:
            note = miditoolkit.Note(
                velocity=80,
                pitch=pc,
                start=time,
                end=time + time_per_step
            )
            piano.notes.append(note)

        # Add melody notes consecutively within the chord step
        num_notes = len(melody_pitches)
        if num_notes > 0:
            note_duration = time_per_step // num_notes
            for i, pitch in enumerate(melody_pitches):
                if pitch >= 0:
                    note = miditoolkit.Note(
                        velocity=100,
                        pitch=pitch,
                        start=time + i * note_duration,
                        end=time + (i + 1) * note_duration
                    )
                    piano.notes.append(note)

        time += time_per_step

    midi_obj.instruments.append(piano)
    midi_obj.dump(output_path)

chord_seq1 = [
    [60, 64, 67],  # C
    [62, 65, 69],  # Dm
    [64, 67, 71],  # Em
    [65, 69, 72],  # F
    [67, 71, 74],  # G
    [69, 72, 76],  # Am
    [71, 74, 77],  # Bdim

    [60, 64, 67],  # C
    [65, 69, 72],  # F
    [67, 71, 74],  # G

    [62, 65, 69],  # Dm
    [60, 64, 67],  # C
    [64, 67, 71],  # Em
    [69, 72, 76],  # Am

    [65, 69, 72],  # F
    [67, 71, 74],  # G
    [60, 64, 67],  # C
    [62, 65, 69],  # Dm

    [64, 67, 71],  # Em
    [65, 69, 72],  # F
    [67, 71, 74],  # G
    [69, 72, 76],  # Am

    [60, 64, 67],  # C
    [65, 69, 72],  # F
    [67, 71, 74],  # G
    [60, 64, 67],  # C

    [62, 65, 69],  # Dm
    [64, 67, 71],  # Em
    [60, 64, 67],  # C
    [67, 71, 74],  # G
]
melody_seq1 = []
for chord in chord_seq1:
  melody_seq1.append(generate_melody(model2, chord))
print(melody_seq1)

create_midi(chord_seq1, melody_seq1, "generated_output.mid")
fs = FluidSynth("FluidR3Mono_GM.sf3")
fs.midi_to_audio("generated_output.mid", "generated_output.wav")
display(Audio("generated_output.wav"))

ex2 = midi_files[1]
# ex = "/content/drive/MyDrive/CSE253/assignment2/unzipped/midis/Bach, Carl Philipp Emanuel, Menuet in F major, H.218, UTtgkpZADqs.mid"
examples2 = extract_map(ex2)

chord_seq2 = []
for chords, _ in examples2:
  chord_seq2.append(chords)

melody_seq2 = []
for chord in chord_seq2:
  melody_seq2.append(generate_melody(model2, chord))
print(melody_seq2)

create_midi(chord_seq2, melody_seq2, "generated_output3.mid")
fs.midi_to_audio("generated_output3.mid", "generated_output3.wav")
display(Audio("generated_output3.wav"))



"""##Evaluate Model 2"""

def evaluate_perplexity2(model, data_loader, melody_vocab_size=88, device='cuda'):
    model.eval()
    total_loss = 0.0
    total_tokens = 0
    criterion = nn.CrossEntropyLoss(reduction='sum')

    with torch.no_grad():
        for batch in data_loader:
            chords = batch['chords'].to(device)
            melodies = batch['melodies'].to(device)

            outputs, _ = model(chords)
            outputs = outputs.reshape(-1, melody_vocab_size)
            targets = melodies.reshape(-1)

            loss = criterion(outputs, targets)
            total_loss += loss.item()
            total_tokens += targets.size(0)

    avg_loss = total_loss / total_tokens
    perplexity = math.exp(avg_loss)
    return perplexity

ppl2 = evaluate_perplexity2(model2, test_loader2, device='cuda')
print(f"Test Perplexity for Model #2: {ppl2:.2f}")

